#!/usr/bin/env bash
# Assemble "Wu Wei.app" around an already-built binary.
#
#   make-bundle.sh <binary> <version> [out-dir]
#
# <binary>   path to a (preferably universal) wu-wei executable
# <version>  X.Y.Z, substituted into Info.plist
# [out-dir]  where "Wu Wei.app" is written (default: dist/)
#
# Produces an ad-hoc-signed bundle: it runs once the user clears the
# quarantine flag (right-click -> Open). Real Developer ID signing and
# notarization are not wired up yet.
set -euo pipefail
unset CDPATH  # otherwise `cd` in the command substitution below echoes the path

BIN=${1:?usage: make-bundle.sh <binary> <version> [out-dir]}
VERSION=${2:?usage: make-bundle.sh <binary> <version> [out-dir]}
OUTDIR=${3:-dist}

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

APP="$OUTDIR/Wu Wei.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

install -m 755 "$BIN" "$APP/Contents/MacOS/wu-wei"

# Icons are generated by the binary itself.
"$BIN" emit-icons "$OUTDIR/_icons"
cp "$OUTDIR/_icons/wu-wei.icns" "$APP/Contents/Resources/wu-wei.icns"
rm -rf "$OUTDIR/_icons"

sed "s/__VERSION__/$VERSION/g" "$HERE/Info.plist" > "$APP/Contents/Info.plist"
printf 'APPL????' > "$APP/Contents/PkgInfo"

codesign --force --deep --sign - "$APP"
echo "built $APP"
